name: publish

on: [push]

jobs:
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Setup GCP Service Account
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_email: ${{ secrets.plucky-paratext-274008@appspot.gserviceaccount.com }}
          service_account_key: ${{ secrets.580cd64508e3feb08f121863867c618122fb0281 }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Build
        run: |
          docker build -t gcr.io/${{ secrets.plucky-paratext-274008 }}/StylahApplication:latest .

      - name: Push
        run: |
          docker push gcr.io/${{ secrets.plucky-paratext-274008 }}/StylahApplication:latest

      - name: Deploy
        run: |
          gcloud run deploy StylahApplication \
          --region europe-west1 \
          --image gcr.io/${{ secrets.plucky-paratext-274008 }}/StylahApplication \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.plucky-paratext-274008 }}
